name: windows-build-static

on: [push, pull_request]
  
jobs:
 build-windows-static:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
       lfs: 'true'
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Set env
      id: env
      run: |
        xmake g -c
    - name: Shipping
      run: |
        xmake f -m release --toolchain=clang-cl -c -y -v -k static --policies=build.ccache:n
        xmake -y -v
    - name: UploadShipping
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: build